package com.financetoy.order;

public enum OrderEventType {
    ORDER_RECEIVED,
    CASH_RESERVED,
    EXECUTION_ATTEMPTED,
    EXECUTION_CONFIRMED,
    EXECUTION_REJECTED,
    EXECUTION_TIMEOUT,
    ORDER_CANCELLED,
    COMPENSATION_APPLIED,
    DUPLICATE_CALLBACK_IGNORED,
    DELAYED_CALLBACK_RECEIVED
}
